# ===================================
#  List Behavior Config
# ===================================

title: magiczne.resume::lang.menu.education
list: $/magiczne/resume/models/education/columns.yaml
modelClass: Magiczne\Resume\Models\Education
recordUrl: 'magiczne/resume/education/update/:id'

showSetup: true
showCheckboxes: true
recordsPerPage: 20
noRecordsMessage: 'backend::lang.list.no_records'

toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

