# ===================================
#  Reorder Behavior Config
# ===================================

title: 'backend::lang.reorder.default_title'
modelClass: Magiczne\Resume\Models\Experience

nameFrom: time_period

toolbar:
    buttons: reorder_toolbar
