# ===================================
#  List Behavior Config
# ===================================

title: magiczne.resume::lang.menu.languages
list: $/magiczne/resume/models/language/columns.yaml
modelClass: Magiczne\Resume\Models\Language
recordUrl: 'magiczne/resume/languages/update/:id'

showSetup: true
showCheckboxes: true
recordsPerPage: 20
noRecordsMessage: 'backend::lang.list.no_records'

toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

