# ===================================
#  List Behavior Config
# ===================================

title: magiczne.resume::lang.menu.social
list: $/magiczne/resume/models/social/columns.yaml
modelClass: Magiczne\Resume\Models\Social
recordUrl: 'magiczne/resume/socials/update/:id'

showSetup: true
showCheckboxes: true
recordsPerPage: 20
noRecordsMessage: 'backend::lang.list.no_records'

toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

