# ===================================
#  List Behavior Config
# ===================================

title: magiczne.resume::lang.menu.info
list: $/magiczne/resume/models/info/columns.yaml
modelClass: Magiczne\Resume\Models\Info
recordUrl: 'magiczne/resume/info/update/:id'

showSetup: true
showCheckboxes: true
recordsPerPage: 20
noRecordsMessage: 'backend::lang.list.no_records'

toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

