# ===================================
#  Reorder Behavior Config
# ===================================

title: 'backend::lang.reorder.default_title'
modelClass: Magiczne\Resume\Models\Info

nameFrom: title

toolbar:
    buttons: reorder_toolbar
